// Code generated by MockGen. DO NOT EDIT.
// Source: internal/worker/types.go

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
)

// MockRedisTaskProcessor is a mock of RedisTaskProcessor interface.
type MockRedisTaskProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockRedisTaskProcessorMockRecorder
}

// MockRedisTaskProcessorMockRecorder is the mock recorder for MockRedisTaskProcessor.
type MockRedisTaskProcessorMockRecorder struct {
	mock *MockRedisTaskProcessor
}

// NewMockRedisTaskProcessor creates a new mock instance.
func NewMockRedisTaskProcessor(ctrl *gomock.Controller) *MockRedisTaskProcessor {
	mock := &MockRedisTaskProcessor{ctrl: ctrl}
	mock.recorder = &MockRedisTaskProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisTaskProcessor) EXPECT() *MockRedisTaskProcessorMockRecorder {
	return m.recorder
}

// HandleDeleteSessionsTask mocks base method.
func (m *MockRedisTaskProcessor) HandleDeleteSessionsTask(ctx context.Context, t *asynq.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDeleteSessionsTask", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleDeleteSessionsTask indicates an expected call of HandleDeleteSessionsTask.
func (mr *MockRedisTaskProcessorMockRecorder) HandleDeleteSessionsTask(ctx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDeleteSessionsTask", reflect.TypeOf((*MockRedisTaskProcessor)(nil).HandleDeleteSessionsTask), ctx, t)
}

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeTaskDeleteSessions mocks base method.
func (m *MockTaskDistributor) DistributeTaskDeleteSessions(ctx context.Context, jtis []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeTaskDeleteSessions", ctx, jtis)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskDeleteSessions indicates an expected call of DistributeTaskDeleteSessions.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskDeleteSessions(ctx, jtis interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskDeleteSessions", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskDeleteSessions), ctx, jtis)
}
