// Code generated by MockGen. DO NOT EDIT.
// Source: internal/worker/types.go

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
)

// MockTaskProcessor is a mock of TaskProcessor interface.
type MockTaskProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskProcessorMockRecorder
}

// MockTaskProcessorMockRecorder is the mock recorder for MockTaskProcessor.
type MockTaskProcessorMockRecorder struct {
	mock *MockTaskProcessor
}

// NewMockTaskProcessor creates a new mock instance.
func NewMockTaskProcessor(ctrl *gomock.Controller) *MockTaskProcessor {
	mock := &MockTaskProcessor{ctrl: ctrl}
	mock.recorder = &MockTaskProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskProcessor) EXPECT() *MockTaskProcessorMockRecorder {
	return m.recorder
}

// HandleDeleteSessionsTask mocks base method.
func (m *MockTaskProcessor) HandleDeleteSessionsTask(ctx context.Context, t *asynq.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDeleteSessionsTask", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleDeleteSessionsTask indicates an expected call of HandleDeleteSessionsTask.
func (mr *MockTaskProcessorMockRecorder) HandleDeleteSessionsTask(ctx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDeleteSessionsTask", reflect.TypeOf((*MockTaskProcessor)(nil).HandleDeleteSessionsTask), ctx, t)
}

// Start mocks base method.
func (m *MockTaskProcessor) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockTaskProcessorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTaskProcessor)(nil).Start))
}

// Stop mocks base method.
func (m *MockTaskProcessor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockTaskProcessorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTaskProcessor)(nil).Stop))
}

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// DistributeTaskDeleteSessions mocks base method.
func (m *MockTaskDistributor) DistributeTaskDeleteSessions(ctx context.Context, jtis []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeTaskDeleteSessions", ctx, jtis)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskDeleteSessions indicates an expected call of DistributeTaskDeleteSessions.
func (mr *MockTaskDistributorMockRecorder) DistributeTaskDeleteSessions(ctx, jtis interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskDeleteSessions", reflect.TypeOf((*MockTaskDistributor)(nil).DistributeTaskDeleteSessions), ctx, jtis)
}
