services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql-db
    ports:
      - "3306:3306"
    volumes:
      # 备份数据
      - ./mysql-data:/var/lib/mysql
      # 初始化数据
      - ./db/commands:/docker-entrypoint-initdb.d

networks:
  default:
    name: app-network
