events {
        worker_connections 1024;
}
http {
        # 定义 main 日志格式
        log_format main
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_device_id" "$http_x_forwarded_for" '
        'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';

        # 指定路径
        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;

        server {
                listen 80;
                server_name localhost;

                location /api/ {
                        proxy_pass http://host.docker.internal:8080;

                        proxy_set_header Host $host; # 传递原主机头
                        proxy_set_header X-Real-IP $remote_addr; # 传递真实 IP
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 传递经过的代理 IP
                        proxy_set_header X-Forwarded-Proto $scheme; # 传递协议
                }

                location /swagger/ {
                        proxy_pass http://host.docker.internal:8080;

                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                }

                location /grafana/ {
                        proxy_pass http://grafana:3000;

                        proxy_set_header Host $host; # 传递原主机头
                        proxy_set_header X-Real-IP $remote_addr; # 传递真实 IP
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 传递经过的代理 IP
                        proxy_set_header X-Forwarded-Proto $scheme; # 传递协议
                }

                location /prometheus/ {
                        proxy_pass http://prometheus:9090;

                        proxy_set_header Host $host; # 传递原主机头
                        proxy_set_header X-Real-IP $remote_addr; # 传递真实 IP
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # 传递经过的代理 IP
                        proxy_set_header X-Forwarded-Proto $scheme; # 传递协议
                }


                location / {
                        root /usr/share/nginx/html;
                        index index.html;
                }
        }
}