// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raozhaizhu/go-estate/internal/controller/daily_data (interfaces: Service)

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/raozhaizhu/go-estate/internal/db/sqlc"
	dailyData "github.com/raozhaizhu/go-estate/internal/service/daily_data"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAllData mocks base method.
func (m *MockService) GetAllData(arg0 context.Context) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllData", arg0)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllData indicates an expected call of GetAllData.
func (mr *MockServiceMockRecorder) GetAllData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllData", reflect.TypeOf((*MockService)(nil).GetAllData), arg0)
}

// GetDataByDay mocks base method.
func (m *MockService) GetDataByDay(arg0 context.Context, arg1 dailyData.GetDataByDayInput) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByDay", arg0, arg1)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByDay indicates an expected call of GetDataByDay.
func (mr *MockServiceMockRecorder) GetDataByDay(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByDay", reflect.TypeOf((*MockService)(nil).GetDataByDay), arg0, arg1)
}

// GetDataByPeriod mocks base method.
func (m *MockService) GetDataByPeriod(arg0 context.Context, arg1 dailyData.GetDataByPeriodInput) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByPeriod", arg0, arg1)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByPeriod indicates an expected call of GetDataByPeriod.
func (mr *MockServiceMockRecorder) GetDataByPeriod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByPeriod", reflect.TypeOf((*MockService)(nil).GetDataByPeriod), arg0, arg1)
}
