// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raozhaizhu/go-estate/internal/controller/daily_data (interfaces: DailyDataQuerier)

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/raozhaizhu/go-estate/internal/db/sqlc"
	service "github.com/raozhaizhu/go-estate/internal/service/daily_data"
)

// MockDailyDataQuerier is a mock of DailyDataQuerier interface.
type MockDailyDataQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockDailyDataQuerierMockRecorder
}

// MockDailyDataQuerierMockRecorder is the mock recorder for MockDailyDataQuerier.
type MockDailyDataQuerierMockRecorder struct {
	mock *MockDailyDataQuerier
}

// NewMockDailyDataQuerier creates a new mock instance.
func NewMockDailyDataQuerier(ctrl *gomock.Controller) *MockDailyDataQuerier {
	mock := &MockDailyDataQuerier{ctrl: ctrl}
	mock.recorder = &MockDailyDataQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDailyDataQuerier) EXPECT() *MockDailyDataQuerierMockRecorder {
	return m.recorder
}

// GetAllData mocks base method.
func (m *MockDailyDataQuerier) GetAllData(arg0 context.Context) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllData", arg0)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllData indicates an expected call of GetAllData.
func (mr *MockDailyDataQuerierMockRecorder) GetAllData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllData", reflect.TypeOf((*MockDailyDataQuerier)(nil).GetAllData), arg0)
}

// GetDataByDay mocks base method.
func (m *MockDailyDataQuerier) GetDataByDay(arg0 context.Context, arg1 service.GetDataByDayInput) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByDay", arg0, arg1)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByDay indicates an expected call of GetDataByDay.
func (mr *MockDailyDataQuerierMockRecorder) GetDataByDay(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByDay", reflect.TypeOf((*MockDailyDataQuerier)(nil).GetDataByDay), arg0, arg1)
}

// GetDataByPeriod mocks base method.
func (m *MockDailyDataQuerier) GetDataByPeriod(arg0 context.Context, arg1 service.GetDataByPeriodInput) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByPeriod", arg0, arg1)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByPeriod indicates an expected call of GetDataByPeriod.
func (mr *MockDailyDataQuerierMockRecorder) GetDataByPeriod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByPeriod", reflect.TypeOf((*MockDailyDataQuerier)(nil).GetDataByPeriod), arg0, arg1)
}
