// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raozhaizhu/go-estate/pkg/object_store (interfaces: StorageService)

// Package mock_object_store is a generated GoMock package.
package mock_object_store

import (
	context "context"
	reflect "reflect"
	testing "testing"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// CleanTestObjectStore mocks base method.
func (m *MockStorageService) CleanTestObjectStore(arg0 *testing.T) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanTestObjectStore", arg0)
}

// CleanTestObjectStore indicates an expected call of CleanTestObjectStore.
func (mr *MockStorageServiceMockRecorder) CleanTestObjectStore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanTestObjectStore", reflect.TypeOf((*MockStorageService)(nil).CleanTestObjectStore), arg0)
}

// EnsureFileExists mocks base method.
func (m *MockStorageService) EnsureFileExists(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureFileExists", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureFileExists indicates an expected call of EnsureFileExists.
func (mr *MockStorageServiceMockRecorder) EnsureFileExists(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureFileExists", reflect.TypeOf((*MockStorageService)(nil).EnsureFileExists), arg0, arg1, arg2)
}

// GetDownloadUrl mocks base method.
func (m *MockStorageService) GetDownloadUrl(arg0 context.Context, arg1, arg2 string, arg3 time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadUrl", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadUrl indicates an expected call of GetDownloadUrl.
func (mr *MockStorageServiceMockRecorder) GetDownloadUrl(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadUrl", reflect.TypeOf((*MockStorageService)(nil).GetDownloadUrl), arg0, arg1, arg2, arg3)
}

// GetPostPolicy mocks base method.
func (m *MockStorageService) GetPostPolicy(arg0 context.Context, arg1, arg2 string, arg3 time.Duration, arg4, arg5 int64, arg6 string) (string, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostPolicy", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPostPolicy indicates an expected call of GetPostPolicy.
func (mr *MockStorageServiceMockRecorder) GetPostPolicy(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostPolicy", reflect.TypeOf((*MockStorageService)(nil).GetPostPolicy), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}
