// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raozhaizhu/go-estate/service (interfaces: DailyDataServiceInterface)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	db "github.com/raozhaizhu/go-estate/db/sqlc"
)

// MockDailyDataServiceInterface is a mock of DailyDataServiceInterface interface.
type MockDailyDataServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDailyDataServiceInterfaceMockRecorder
}

// MockDailyDataServiceInterfaceMockRecorder is the mock recorder for MockDailyDataServiceInterface.
type MockDailyDataServiceInterfaceMockRecorder struct {
	mock *MockDailyDataServiceInterface
}

// NewMockDailyDataServiceInterface creates a new mock instance.
func NewMockDailyDataServiceInterface(ctrl *gomock.Controller) *MockDailyDataServiceInterface {
	mock := &MockDailyDataServiceInterface{ctrl: ctrl}
	mock.recorder = &MockDailyDataServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDailyDataServiceInterface) EXPECT() *MockDailyDataServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAllData mocks base method.
func (m *MockDailyDataServiceInterface) GetAllData(arg0 context.Context) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllData", arg0)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllData indicates an expected call of GetAllData.
func (mr *MockDailyDataServiceInterfaceMockRecorder) GetAllData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllData", reflect.TypeOf((*MockDailyDataServiceInterface)(nil).GetAllData), arg0)
}

// GetDataByDay mocks base method.
func (m *MockDailyDataServiceInterface) GetDataByDay(arg0 context.Context, arg1 time.Time) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByDay", arg0, arg1)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByDay indicates an expected call of GetDataByDay.
func (mr *MockDailyDataServiceInterfaceMockRecorder) GetDataByDay(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByDay", reflect.TypeOf((*MockDailyDataServiceInterface)(nil).GetDataByDay), arg0, arg1)
}

// GetDataByPeriod mocks base method.
func (m *MockDailyDataServiceInterface) GetDataByPeriod(arg0 context.Context, arg1, arg2 time.Time) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByPeriod", arg0, arg1, arg2)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByPeriod indicates an expected call of GetDataByPeriod.
func (mr *MockDailyDataServiceInterfaceMockRecorder) GetDataByPeriod(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByPeriod", reflect.TypeOf((*MockDailyDataServiceInterface)(nil).GetDataByPeriod), arg0, arg1, arg2)
}
