// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type DailyDatum struct {
	ID          int32          `json:"id"`
	Date        time.Time      `json:"date"`
	Region      int16          `json:"region"`
	Category    string         `json:"category"`
	LicenseNo   string         `json:"license_no"`
	ProjectName string         `json:"project_name"`
	HouseCount  int16          `json:"house_count"`
	Area        string         `json:"area"`
	AvgPrice    sql.NullString `json:"avg_price"`
}
