// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetAllData(ctx context.Context) ([]DailyDatum, error)
	GetDataByDay(ctx context.Context) ([]DailyDatum, error)
	GetDataByPeriod(ctx context.Context) ([]DailyDatum, error)
}

var _ Querier = (*Queries)(nil)
