// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sale.sql

package db

import (
	"context"
)

const getAllData = `-- name: GetAllData :many
SELECT
        id, date, region, category, license_no, project_name, house_count, area, avg_price
FROM
        daily_data
`

func (q *Queries) GetAllData(ctx context.Context) ([]DailyDatum, error) {
	rows, err := q.db.QueryContext(ctx, getAllData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyDatum{}
	for rows.Next() {
		var i DailyDatum
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Region,
			&i.Category,
			&i.LicenseNo,
			&i.ProjectName,
			&i.HouseCount,
			&i.Area,
			&i.AvgPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataByDay = `-- name: GetDataByDay :many
SELECT
        id, date, region, category, license_no, project_name, house_count, area, avg_price
FROM
        daily_data
WHERE
        date = $1
`

func (q *Queries) GetDataByDay(ctx context.Context) ([]DailyDatum, error) {
	rows, err := q.db.QueryContext(ctx, getDataByDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyDatum{}
	for rows.Next() {
		var i DailyDatum
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Region,
			&i.Category,
			&i.LicenseNo,
			&i.ProjectName,
			&i.HouseCount,
			&i.Area,
			&i.AvgPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataByPeriod = `-- name: GetDataByPeriod :many
SELECT
        id, date, region, category, license_no, project_name, house_count, area, avg_price
FROM
        daily_data
WHERE
        date >= $1
        AND date <= $2
`

func (q *Queries) GetDataByPeriod(ctx context.Context) ([]DailyDatum, error) {
	rows, err := q.db.QueryContext(ctx, getDataByPeriod)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyDatum{}
	for rows.Next() {
		var i DailyDatum
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Region,
			&i.Category,
			&i.LicenseNo,
			&i.ProjectName,
			&i.HouseCount,
			&i.Area,
			&i.AvgPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
