// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raozhaizhu/go-estate/internal/dao/cache (interfaces: SessionCache)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cache "github.com/raozhaizhu/go-estate/internal/dao/cache"
)

// MockSessionCache is a mock of SessionCache interface.
type MockSessionCache struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCacheMockRecorder
}

// MockSessionCacheMockRecorder is the mock recorder for MockSessionCache.
type MockSessionCacheMockRecorder struct {
	mock *MockSessionCache
}

// NewMockSessionCache creates a new mock instance.
func NewMockSessionCache(ctrl *gomock.Controller) *MockSessionCache {
	mock := &MockSessionCache{ctrl: ctrl}
	mock.recorder = &MockSessionCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCache) EXPECT() *MockSessionCacheMockRecorder {
	return m.recorder
}

// AddNewSession mocks base method.
func (m *MockSessionCache) AddNewSession(arg0 context.Context, arg1 cache.AddNewSessionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewSession indicates an expected call of AddNewSession.
func (mr *MockSessionCacheMockRecorder) AddNewSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewSession", reflect.TypeOf((*MockSessionCache)(nil).AddNewSession), arg0, arg1)
}

// BatchDelete mocks base method.
func (m *MockSessionCache) BatchDelete(arg0 context.Context, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockSessionCacheMockRecorder) BatchDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockSessionCache)(nil).BatchDelete), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockSessionCache) GetSession(arg0 context.Context, arg1 string) (*cache.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(*cache.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionCacheMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionCache)(nil).GetSession), arg0, arg1)
}
