// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raozhaizhu/go-estate/internal/dao/cache (interfaces: Cache)

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"
	testing "testing"
	time "time"

	gomock "github.com/golang/mock/gomock"
	cache "github.com/raozhaizhu/go-estate/internal/dao/cache"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// AddNewSession mocks base method.
func (m *MockCache) AddNewSession(arg0 context.Context, arg1 cache.AddNewSessionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewSession indicates an expected call of AddNewSession.
func (mr *MockCacheMockRecorder) AddNewSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewSession", reflect.TypeOf((*MockCache)(nil).AddNewSession), arg0, arg1)
}

// BatchDelete mocks base method.
func (m *MockCache) BatchDelete(arg0 context.Context, arg1 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchDelete indicates an expected call of BatchDelete.
func (mr *MockCacheMockRecorder) BatchDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchDelete", reflect.TypeOf((*MockCache)(nil).BatchDelete), arg0, arg1)
}

// CleanTestCache mocks base method.
func (m *MockCache) CleanTestCache(arg0 *testing.T) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanTestCache", arg0)
}

// CleanTestCache indicates an expected call of CleanTestCache.
func (mr *MockCacheMockRecorder) CleanTestCache(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanTestCache", reflect.TypeOf((*MockCache)(nil).CleanTestCache), arg0)
}

// Close mocks base method.
func (m *MockCache) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacheMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCache)(nil).Close))
}

// GetDailyData mocks base method.
func (m *MockCache) GetDailyData(arg0 context.Context, arg1, arg2 string, arg3 interface{}) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyData", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyData indicates an expected call of GetDailyData.
func (mr *MockCacheMockRecorder) GetDailyData(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyData", reflect.TypeOf((*MockCache)(nil).GetDailyData), arg0, arg1, arg2, arg3)
}

// GetSession mocks base method.
func (m *MockCache) GetSession(arg0 context.Context, arg1 string) (*cache.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(*cache.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockCacheMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockCache)(nil).GetSession), arg0, arg1)
}

// IncrIPCnt mocks base method.
func (m *MockCache) IncrIPCnt(arg0 context.Context, arg1 string, arg2 time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrIPCnt", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrIPCnt indicates an expected call of IncrIPCnt.
func (mr *MockCacheMockRecorder) IncrIPCnt(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrIPCnt", reflect.TypeOf((*MockCache)(nil).IncrIPCnt), arg0, arg1, arg2)
}

// SetDailyData mocks base method.
func (m *MockCache) SetDailyData(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDailyData", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDailyData indicates an expected call of SetDailyData.
func (mr *MockCacheMockRecorder) SetDailyData(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDailyData", reflect.TypeOf((*MockCache)(nil).SetDailyData), arg0, arg1, arg2, arg3, arg4)
}
