// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raozhaizhu/go-estate/pkg/token (interfaces: Maker)

// Package mock_token is a generated GoMock package.
package mock_token

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	db "github.com/raozhaizhu/go-estate/internal/dao/sqlc"
	userDomain "github.com/raozhaizhu/go-estate/internal/domain/user"
	util "github.com/raozhaizhu/go-estate/internal/util"
	token "github.com/raozhaizhu/go-estate/pkg/token"
)

// MockMaker is a mock of Maker interface.
type MockMaker struct {
	ctrl     *gomock.Controller
	recorder *MockMakerMockRecorder
}

// MockMakerMockRecorder is the mock recorder for MockMaker.
type MockMakerMockRecorder struct {
	mock *MockMaker
}

// NewMockMaker creates a new mock instance.
func NewMockMaker(ctrl *gomock.Controller) *MockMaker {
	mock := &MockMaker{ctrl: ctrl}
	mock.recorder = &MockMakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaker) EXPECT() *MockMakerMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockMaker) CreateToken(arg0 string, arg1 userDomain.Role, arg2 time.Duration, arg3 token.TokenType) (string, *token.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*token.Payload)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockMakerMockRecorder) CreateToken(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockMaker)(nil).CreateToken), arg0, arg1, arg2, arg3)
}

// ForgeTokenPair mocks base method.
func (m *MockMaker) ForgeTokenPair(arg0 *db.User, arg1 *util.Config) (string, string, *token.Payload, *token.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgeTokenPair", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*token.Payload)
	ret3, _ := ret[3].(*token.Payload)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// ForgeTokenPair indicates an expected call of ForgeTokenPair.
func (mr *MockMakerMockRecorder) ForgeTokenPair(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgeTokenPair", reflect.TypeOf((*MockMaker)(nil).ForgeTokenPair), arg0, arg1)
}

// VerifyToken mocks base method.
func (m *MockMaker) VerifyToken(arg0 string, arg1 token.TokenType) (*token.Payload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", arg0, arg1)
	ret0, _ := ret[0].(*token.Payload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockMakerMockRecorder) VerifyToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockMaker)(nil).VerifyToken), arg0, arg1)
}
