// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type DailyDatum struct {
	ID          int32          `json:"id"`
	Date        time.Time      `json:"date"`
	Region      int16          `json:"region"`
	Category    string         `json:"category"`
	LicenseNo   string         `json:"license_no"`
	ProjectName string         `json:"project_name"`
	HouseCount  int16          `json:"house_count"`
	Area        string         `json:"area"`
	AvgPrice    sql.NullString `json:"avg_price"`
}

type Session struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	DeviceID  string    `json:"device_id"`
	UserAgent string    `json:"user_agent"`
	ClientIp  string    `json:"client_ip"`
	IsBlocked bool      `json:"is_blocked"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID                int32     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	Role              int16     `json:"role"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
