// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"
	"strings"
	"time"
)

const blockSessionsByIDs = `-- name: BlockSessionsByIDs :exec
UPDATE
        ` + "`" + `sessions` + "`" + `
SET
        is_blocked = TRUE
WHERE
        id IN (/*SLICE:ids*/?)
`

func (q *Queries) BlockSessionsByIDs(ctx context.Context, ids []string) error {
	query := blockSessionsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO
        ` + "`" + `sessions` + "`" + `(
                id,
                username,
                device_id,
                user_agent,
                client_ip,
                is_blocked,
                expires_at
        )
VALUES
        (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	DeviceID  string    `json:"device_id"`
	UserAgent string    `json:"user_agent"`
	ClientIp  string    `json:"client_ip"`
	IsBlocked bool      `json:"is_blocked"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Username,
		arg.DeviceID,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	return err
}

const getActiveSessionIDsByUserDeviceForUpdate = `-- name: GetActiveSessionIDsByUserDeviceForUpdate :many
SELECT
        id
FROM
        ` + "`" + `sessions` + "`" + `
WHERE
        username = ?
        AND device_id = ?
        AND is_blocked = false FOR
UPDATE
`

type GetActiveSessionIDsByUserDeviceForUpdateParams struct {
	Username string `json:"username"`
	DeviceID string `json:"device_id"`
}

func (q *Queries) GetActiveSessionIDsByUserDeviceForUpdate(ctx context.Context, arg GetActiveSessionIDsByUserDeviceForUpdateParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSessionIDsByUserDeviceForUpdate, arg.Username, arg.DeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT
        id, username, device_id, user_agent, client_ip, is_blocked, expires_at, created_at
FROM
        ` + "`" + `sessions` + "`" + `
WHERE
        id = ?
LIMIT
        1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DeviceID,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionIDsByUsernameForUpdate = `-- name: GetSessionIDsByUsernameForUpdate :many
SELECT
        id
FROM
        ` + "`" + `sessions` + "`" + `
WHERE
        username = ?
        AND is_blocked = false FOR
UPDATE
`

func (q *Queries) GetSessionIDsByUsernameForUpdate(ctx context.Context, username string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getSessionIDsByUsernameForUpdate, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
