// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: use_query_records.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getUserQueryRecord = `-- name: GetUserQueryRecord :execresult
SELECT
        id, username, query_type, start_date, end_date, created_at
FROM
        ` + "`" + `user_query_records` + "`" + `
WHERE
        username = ?
        AND query_type = ?
        AND start_date = ?
        AND end_date = ?
`

type GetUserQueryRecordParams struct {
	Username  string    `json:"username"`
	QueryType int8      `json:"query_type"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetUserQueryRecord(ctx context.Context, arg GetUserQueryRecordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, getUserQueryRecord,
		arg.Username,
		arg.QueryType,
		arg.StartDate,
		arg.EndDate,
	)
}
