// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO
        users(
                username,
                hashed_password,
                email,
                avatar_key,
                role
        )
VALUES
        (
                ?,
                ?,
                ?,
                CASE
                        WHEN ? = '' THEN 'default_avatar.png'
                        ELSE ?
                END,
                COALESCE(?, 1)
        )
`

type CreateUserParams struct {
	Username       string      `json:"username"`
	HashedPassword string      `json:"hashed_password"`
	Email          string      `json:"email"`
	AvatarKey      interface{} `json:"avatar_key"`
	Role           interface{} `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.Email,
		arg.AvatarKey,
		arg.AvatarKey,
		arg.Role,
	)
}

const getUser = `-- name: GetUser :one
SELECT
        id, username, hashed_password, email, avatar_key, role, password_changed_at, created_at
FROM
        users
WHERE
        username = ?
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Email,
		&i.AvatarKey,
		&i.Role,
		&i.PasswordChangedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE
        users
SET
        hashed_password = COALESCE(?, hashed_password),
        password_changed_at = COALESCE(
                ?,
                password_changed_at
        ),
        email = COALESCE(?, email),
        avatar_key = COALESCE(?, avatar_key)
WHERE
        username = ?
`

type UpdateUserParams struct {
	HashedPassword    sql.NullString `json:"hashed_password"`
	PasswordChangedAt sql.NullTime   `json:"password_changed_at"`
	Email             sql.NullString `json:"email"`
	AvatarKey         sql.NullString `json:"avatar_key"`
	Username          string         `json:"username"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.HashedPassword,
		arg.PasswordChangedAt,
		arg.Email,
		arg.AvatarKey,
		arg.Username,
	)
}
