// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raozhaizhu/go-estate/internal/dao/sqlc (interfaces: DailyDataStore)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	db "github.com/raozhaizhu/go-estate/internal/dao/sqlc"
)

// MockDailyDataStore is a mock of DailyDataStore interface.
type MockDailyDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockDailyDataStoreMockRecorder
}

// MockDailyDataStoreMockRecorder is the mock recorder for MockDailyDataStore.
type MockDailyDataStoreMockRecorder struct {
	mock *MockDailyDataStore
}

// NewMockDailyDataStore creates a new mock instance.
func NewMockDailyDataStore(ctrl *gomock.Controller) *MockDailyDataStore {
	mock := &MockDailyDataStore{ctrl: ctrl}
	mock.recorder = &MockDailyDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDailyDataStore) EXPECT() *MockDailyDataStoreMockRecorder {
	return m.recorder
}

// GetAllData mocks base method.
func (m *MockDailyDataStore) GetAllData(arg0 context.Context) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllData", arg0)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllData indicates an expected call of GetAllData.
func (mr *MockDailyDataStoreMockRecorder) GetAllData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllData", reflect.TypeOf((*MockDailyDataStore)(nil).GetAllData), arg0)
}

// GetDataByDay mocks base method.
func (m *MockDailyDataStore) GetDataByDay(arg0 context.Context, arg1 time.Time) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByDay", arg0, arg1)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByDay indicates an expected call of GetDataByDay.
func (mr *MockDailyDataStoreMockRecorder) GetDataByDay(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByDay", reflect.TypeOf((*MockDailyDataStore)(nil).GetDataByDay), arg0, arg1)
}

// GetDataByPeriod mocks base method.
func (m *MockDailyDataStore) GetDataByPeriod(arg0 context.Context, arg1 db.GetDataByPeriodParams) ([]db.DailyDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataByPeriod", arg0, arg1)
	ret0, _ := ret[0].([]db.DailyDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataByPeriod indicates an expected call of GetDataByPeriod.
func (mr *MockDailyDataStoreMockRecorder) GetDataByPeriod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataByPeriod", reflect.TypeOf((*MockDailyDataStore)(nil).GetDataByPeriod), arg0, arg1)
}
